### ISSUE TITLE
Markers click event broken in version 2.1.0, worked in 2.0.20

### ISSUE THREAD

**Issue by mikepugh** [angular-ui/angular-google-maps#1327]
When upgrading to 2.1.x from 2.0.20 - the Markers directive 'click' event does not evaluate properly to a function. Instead it evaluates the property to a string, which results in an error. 

See plunker for example - initially it is using 2.1.x, open up the Console and try to click on a marker pin and you'll see the error.

Comment out 2.1.0 library and uncomment 2.0.20 library and the click event works fine.

http://plnkr.co/edit/LM3mRzbDHZjFmE8xtpRS?p=preview

**Comment by homerjam** [comment]
I concur

**Comment by victorcl** [comment]
I have the same problem , when I click on a marker I get "Uncaught TypeError: click is not a function"  , only solution is to go back to 2.0 ??

**Comment by ruddct** [comment]
Ditto, seeing the same here

**Comment by poacher2k** [comment]
It seems that the function responsible for getting the function, only is getting the function name.
on line ```3376: click = _this.getProp('click', _this.scope, _this.model);```. Adding ```click = _this.model[click];```to the next line seems to fix the problem. Not sure what the side effects of this is, but at least it works: http://plnkr.co/edit/vdcjsXcCHBZiMMT7xGjH

**Comment by poacher2k** [comment]
Scratch that. Your plnkr works if you remove the quotes around 'clickPin' in index.html.
From: ```click="'clickPin'"```
To: ```click="clickPin"```

Plnkr: http://plnkr.co/edit/1HkApoVGoAMyarCoR3EP?p=preview

**Comment by mikepugh** [comment]
@poacher2k thanks.

I could have sworn I tried that on my real app and it didn't work but maybe I'm just dreaming.

I'll give it a shot and update w/ results.

**Comment by nmccready** [comment]
Yes I apologize about the non-documentation on those changes. I haven't had the time (to do the docs); but the code was done for a long time. Since I have been busier on other project and looking for someone else to take over this I decided to release 2.1.X without the docs otherwise it would never get done. 

The code responsible for deciding what to do with the property is [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/model-key.coffee#L92-L113)

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/model-key.coffee#L92-L113

**Comment by nmccready** [comment]
I'm considering starting an API.md on 2.0.X and updating it for 2.1.X if others are willing to participate. The website to me is a pain for generating clear documentation where Markdown is well suited for it. The website could instead point to the Markdown for documentation and simply be a place to host examples.

**Comment by nmccready** [comment]
#1332

**Comment by wrummler** [comment]
@mikepugh Seems like this one may've been answered for you in light of [your last comment](https://github.com/angular-ui/angular-google-maps/issues/1327#issuecomment-110519367), but feel free to follow-up with details if the question wasn't answered. Thanks.

@nmccready Moved the discussion of API.md to #1384.

Closing this issue.
