### ISSUE TITLE
Many examples not working

### ISSUE THREAD

**Issue by maeishoj** [angular-ui/angular-google-maps#1425]
Hi guys, 

Can you tell me why so many examples in the "example" folder are not working?

I have v 2.1.0 and 2.1.5 and in 2.1.5 it seems even worse. examples that used to work in 2.1.0 are not working in 2.1.5 (e.g. issue-1068-circle-events-doubled.html) in 2.1.0 works and 2.1.5 doesn't:

TypeError: _.get is not a function
    at CircleParentModel.ModelKey.scopeOrModelVal (angular-google-maps_dev_mapped.js:1439)
    at CircleParentModel.ShapeOptionsBuilder.buildOpts (angular-google-maps_dev_mapped.js:2586)
    at CircleParentModel.CircleOptionsBuilder.buildOpts (angular-google-maps_dev_mapped.js:2651)
    at new CircleParentModel (angular-google-maps_dev_mapped.js:4050)
    at angular-google-maps_dev_mapped.js:5552
    at processQueue (angular.js:13137)
    at angular.js:13153
    at Scope.$eval (angular.js:14353)
    at Scope.$digest (angular.js:14169)
    at angular.js:14391(anonymous function) @ angular.js:11562

Anyone noticed this too?

**Comment by nmccready** [comment]
Its not the end of the world ;). #1429 just a fix that broke backwards compat with older lodash.

**Comment by nmccready** [comment]
The examples themselves are broken and thats about it.
