### ISSUE TITLE
[Develop] -  1.3 Info Window

### ISSUE THREAD

**Issue by VerifiedOrganic** [angular-ui/angular-google-maps#724]
I am having some issues getting things to fully work with 1.3. The map works fine however I am stuck with an error "markerCtrl.getScope is not a function" when I attemp to use the window directive inside a marker.

Not sure if I am missing something or if this is just a portion that is not yet compatible with 1.3
