### ISSUE TITLE
Object is not a function after upgrade from 1.0.18

### ISSUE THREAD

**Issue by linkovich2** [angular-ui/angular-google-maps#452]
Hello,
I just updated to v1.1.0 from v1.0.18 and now am receiving the following error: TypeError: object is not a function
    at http://localhost:3000/lib/angular-google-maps/dist/angular-google-maps.js:4006:14

which is:

```
(function() {
  angular.module("google-maps").directive("googleMap", [
    "Map", function(Map) {
      return new Map(); // here
    }
  ]);

}).call(this);
```

I'm not sure at all why this is occurring. Can you point me in the right direction?
